# Generated by Django 4.2.1 on 2023-05-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinMaxFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл .csv с мин. и макс. значениями по столбцам', upload_to='min_max/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='modelfile',
            options={'ordering': ['id'], 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
    ]
