# Generated by Django 4.2.1 on 2023-05-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_minmaxfile_alter_modelfile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minmaxfile',
            options={'ordering': ['id'], 'verbose_name': 'Файл с мин. и макс.', 'verbose_name_plural': 'Файлы с мин. и макс.'},
        ),
    ]
