# Generated by Django 4.2.1 on 2023-05-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_modelfile_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfile',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Не использовать'),
        ),
    ]
